= Hear 'Consume', Think 'Ravage'
Timo Tiuraniemi
1.0, 2022-09-04
:description: People are not consumers.
:keywords: Earth breakdown, common sense

The amount of materials we affluent people of the world extract from nature and the amount of waste we throw back, is vastly more than nature can regenerate.
We destroy ecosystems to points of no recovery.
We simply take too much.

Why this happens is not surprising when you realise what's hiding in plain sight:

> *consume* (transitive verb) 1) to do away with completely : DESTROY
> -- Merriam Webster

The greatest victory of neoliberalism has been to get people to believe that they are consumers and that the more they consume the better.

To break free of this doublespeak, try to exchange "consume" with "ravage" and "consumer" with "destroyer".
For example:

* "Appealing to destroyers' ravaging habits in changing times." -- https://www.forbes.com/sites/forbescommunicationscouncil/2020/06/10/out-with-the-old-appealing-to-consumers-consumption-habits-in-changing-times/[Forbes]
* "Destroyer spending has so far been a bright spot in the U.S. economy." -- https://www.washingtonpost.com/business/2022/06/30/consumer-spending-economy/[Washington Post]
* "Has coronavirus made us more ethical destroyers? It's clear that ravaging is looking very different than it did before Covid." -- https://www.bbc.com/news/business-55630144[BBC]

[#highlighted]#It is not extremist to ask for less complete destruction.#
