= We Need to Talk About the Joneses
Timo Tiuraniemi
1.0, 2022-09-23
:description: A metaphor.
:keywords: metaphor, Earth breakdown, Carbon tunnel vision, capitalism

[#highlighted]#Five families live on a lake island unaware of the world beyond the lake.#
The island is big enough for all of them and the lake has ample fresh drinking water.

The families have built houses and cleared fields that yield enough crops to feed everyone.
Life has its ups and downs, the families quarrel, and harvest sizes vary, but the families can sleep assured that the island can sustain life for the foreseeable future.

The Joneses are the smallest of the families.
John is the father, June the mother and Josie their daughter.
The Joneses live on the northwest corner of the island.
They have the nicest house and a good field.
They like to build things and enjoy the good life.

The island is home to a potent mineral called lio.
The islanders discover a way to use lio as a fertiliser to grow crops much faster.
Furthermore it turns out that lio can also be used to build things faster.

Thanks to lio, many nice things are built and some parts of the island can grow so much food some has to be thrown away.

Over the years the Joneses' field has grown a lot.
To make room for the field and to get more material for building things, the Joneses cut down all of the nearby forests.
The forests are home to many different kinds of animals most of which die as a result.
On the plus side though, the Joneses' house now has an extra wing for Josie and a big patio.

The islanders have formed a council where the adults of the five families regularly meet to discuss common matters.
Recently the council has found out that not only are the forests on the island disappearing, but the water in the lake has started to taste bad.
Due to natural currents in the lake, the water is especially bad in the east and south, but still rather good in the northwest.

The council meets to talk about the water.
Some suspect that the people on the island might have something to do with the water.
The Joneses disagree, and besides their water tastes fine.
After some discussion, the Joneses convince everyone that the change in water quality is because of natural fluctuation and unfortunately there is nothing they can do.

The water quality keeps getting worse.

The council meets again, and this time they have definite proof that the water has been getting worse.
The reason is the use of lio.
Everyone in the council knows that the vast majority of the lio is being used for the benefit of the Joneses.
The Joneses have also cut down even more forests and built a second house just for Josie.
Still, the council makes a decision that every family needs to start making equal efforts to clean the water by reducing their use of lio.

The families get to work. 
However, despite their best intentions the water quality keeps getting worse.
At the same time, the forests on the island have almost been cut down completely and the majority of the animals have died.
The island is windy and barren and despite all of the lio, harverst are smaller every year.

The council has an emergency meeting.

Adults of four families are terrified for the future of the island and their children, but the Joneses look happy.
When the others ask what's there to be happy about, John Jones breaks out the good news.

Building the fourth Jones house made the water quality worse, but a little less than building the third house.
June also believes she can come up with ideas for efficient water cleaning devices.
To this end, the Joneses have mapped out a plan where new houses are built at an increasing pace and everyone trusts in June.
Their calculations show that with this plan, in 30 years, there's a 50% chance the water should still be barely drinkable on most parts of the island.

The other four families get angry.
"Everyone agrees that the water problem is bad, but so is the fact that there are almost no more forests or animals on the island", they say.
The four families demand an alternative plan that doesn't involve building every year more unnecessary houses than the previous year.

The Joneses look baffled.
"But, there is no alternative", John Jones says.
