= Beware of Pacifying Optimism
Timo Tiuraniemi
1.0, 2023-04-XX
:description: TODO
:keywords: Earth breakdown, optimism

:fn-hopeful-pessimism: pass:c,q[footnote:hopeful-pessimism[Mara van der Lugt makes an excellent case for https://aeon.co/essays/in-these-dark-times-the-virtue-we-need-is-hopeful-pessimism[hopeful pessimism as an alternative to optimism].]]
I have always considered myself a careful optimist.
I believe emphasizing the positive aspects is one, but not only{fn-hopeful-pessimism}, way to cope with adversities and increase your chances to make a difference.

However, the more I've been involved with environmental activism the more uneasy I've become about many common optimist statements.
I began thinking about this uneasiness a year ago, but even after a lot of effort, I couldn't quite make sense of it.
Then recently I decided to come back to this problem, and suddenly it all made sense.

In this post I will first introduce two dimensions of optimism and then apply them to the discussion about Earth breakdown.

*NB*: I mean here _optimism about something_ rather than optimism as a general approach on life.

## Conviction Required

:fn-blind-optimism: pass:c,q[footnote:blind-optimism[Hannah Richie makes a similar argument about https://bigthink.com/progress/pessimism-is-a-barrier-to-progress/[mistaking optimism with "blind optimism"], but I feel significantly underestimates the evidence that would be needed for environmental optimism to be grounded in reality.]]
We should first distinguish between dogmatic or *brute optimism* and evidence-based or *grounded optimism*.{fn-blind-optimism}
The difference is about the amount of conviction that's required for a good outcome.

Brute optimism is the view that things are going work out almost no matter what.
This view requires strong conviction to be able to stand against evidence pointing otherwise.

In contrast grounded optimism relies on weaker conviction or no conviction at all.
Grounded optimism takes into account the reality of the situation, and suggests a positive outcome will likely happen because that's what the relevant evidence suggests.
This is a similar view to https://en.wikipedia.org/wiki/Meliorism[meliorism].

## Effort Required

Conviction alone, however, doesn't capture many of the different ways optimism is _used_.
This is why I suggest that the second dimension to optimism is the effort that's required of the audience for a positive outcome.

Whenever we read or hear an optimistic statement, it should also be recognized as https://en.wikipedia.org/wiki/Speech_act[speech act].
To be optimistic about an outcome is not just about passing information, but always (intentionally or not) affects the audience.

When the optimism of the speaker demands that the listener begins to act, I call it *empowering optimism*.
When the effect on the hearer is subduing or to calming, I call it *pacifying optimism*.

## Double-Dichotomy of Optimism

Combining these dimensions forms a double-dichotomy of optimism.

ifeval::["{backend}" == "html5"]

+++
<span>TODO: Picture</span>
+++
endif::[]
ifeval::["{backend}" == "gemini"]
....
Conviction
 required
    ^
    |   Brute        Brute
    |   Pacifying    Empowering
    |
    |   Grounded     Grounded
    |   Pacifying    Empowering
    |
    -----------------------------> Effort
                                   required
....
endif::[]

Depending on what the optimism is about, each of the quadrants will have different characteristics.
To evaluate the usefulness of this double-dichotomy, let's try it on a concrete case.

## Case: Earth Breakdown

Consider optimism about humanity's ability to stop and reverse the climate and ecological breakdown, as it is being discussed especially in the Global North.

ifeval::["{backend}" == "html5"]

+++
<span>TODO: Picture</span>
+++
endif::[]
ifeval::["{backend}" == "gemini"]
....
     Conviction
     required
         ^  
 Brute   |  Climate              Activist
         |  denial               burnout
         |
         |  Climate
         |  delay
         |
         |
         |
Grounded |                       Climate
         |                       justice
         ---------------------------------> Effort
            Pacifying        Empowering     required
....
endif::[]

First, brute empowering optimism about stopping Earth breakdown leads very easily to *activist burnout*.
This is common especially with new activists who give everything to the fight and believe in fast and big changes.
When these changes fail to happen, it can be very hard to recover from emotionally.

Second, grounded empowering optimism about stopping Earth breakdown is what *climate justice* can communicate.
It is grounded in the sense of both taking into account the scale of the systemic changes needed, and the history of successful political movements.
It is empowering because based on this evidence, a positive outcome requires significant efforts from the audience.
Optimism in climate justice relies on mass movements of ordinary people demanding changes.

Third, based on the evidence we have in 2023, there is no grounded pacifying optimism about stopping Earth breakdown.
Unlike in the 1990s, if you take into account the current evidence, you can't communicate a "vote green and wait" message and claim to be grounded.
That ship has sailed, there are only drastic changes ahead.

Lastly, and most importantly, the majority of the hopeful discussion on stopping Earth breakdown is varying degrees of brute pacifying optimism.

*Climate denial* is brute pacifying optimism in the purest form.
Denialists communicate a "don't worry, things are going to work out" message ignoring all of the evidence.
Their optimism rests on pure conviction.
It can for example be conviction that they smarter than all the experts, that it's impossible for humans to harm Earth, or that because experts were wrong before about something and they are wrong now.

Because are getting better at recognizing flat out denialism, many of the same people have recently switched to *climate delay*.
https://www.cambridge.org/core/journals/global-sustainability/article/discourses-of-climate-delay/7B11B722E3E3454BB6212378E32985A7[Climate delay] changes tactics in that it recognizes the severity of the climate crisis, but then picks evidence that supports a pacifying message.
The cherry-picked evidence may be about good progress in only marginally related areas or evidence of https://timotheeparrique.com/a-response-to-paul-krugman-growth-is-not-as-green-as-you-might-think/[too slow progress in a relevant area].
Because some evidence is given, this is optimism that requires less conviction, but can't still hold without it.
Compared to climate denial, climate delay requires conviction on for example "the invisible hand of the market", "progress with a capital P", or the https://www.leolinne.com/wp-content/uploads/2020/12/20200812_DiscoursesClimateDelay_004_EN.jpg[omnipotency of engineers].

Both climate denial and climate delay messaging is pacifying because it demands (almost) nothing from the audience.
The underlying message often reveals as "we smart people can fix this, and all you need to do is vote for less restrictions on us".

Brute pacifying optimism about stopping Earth breakdown is also profoundly insulting and paternalistic.
It is taking the position of the adult in the conversation and giving the listener a figurative pacifier so that they stop shouting.

It's no wonder climate delay messaging is most common with the elite or people in organisations funded by the elite.
It's essentially used by people who benefit from the status quo to try to maintain their power.

## Conclusion

Pacifying optimism isn't always unfounded.
If a house is on fire but everyone is safe and the fire brigade is on their way, you should communicate grounded pacifying optimism.
As a parent, I also understand resorting to brute pacifying optimism to calm a child in a disaster.

However, for a crisis like the climate ecological breakdown, where there is overwhelming evidence that status quo is going to lead to a disaster, pacifying optimism is extremely dangerous.

[#highlighted]#Next time you hear or read someone saying they're optimistic, make sure they aren't actually trying to give you a pacifier to lull you back to sleep when the house is on fire.#
