= This Site Runs on a Raspberry Pi in My Living Room
Timo Tiuraniemi
1.0, 2022-07-17
:description: This site is built with convivial technology principles. Here I break down how it is works.
:keywords: meta, convivial technology, rust
:figure-caption!:

Here's a lovely picture of this site.

This posts breaks down how this little place on the internet works and why I ended up making some unconventional choices.
But first some background.

== Why Do I Need My Own Site?

I've been meaning to set up my own site for ages, but haven't ever found the time to actually do it.

So why now?
Honestly, I only now have something important enought to say.

During a year of https://fosstodon.org/web/@ttiurani[occasional microblogging on Mastodon] I've come up with almost two dozen ideas for posts, that can't be squeezed into toots.
Also I wanted to finally become https://indieweb.org/[self-reliant with the technology I use], and especially never https://theoatmeal.com/comics/reaching_people_2021[rely on corporations for reaching people].

== What's the Site for?

When I decided to go ahead with the project, I wanted to do it without compromises.
This is my site, so it needs to reflect what I think is important.

=== Values

The relevant values, many of which are listed also in the excellent https://small-tech.org/about/#small-technology[small technology], for this site are:

* *Share alike*. All source code is licenced with AGPLv3 and all text with CC By SA 4.0.
* *Private by default*. No tracking and no storing nor logging of any personally identifiable information.
* *Non-commercial*. There is no ulterior motive to make profit. What you see is all there is.
* *Inclusive*. Accessibility is not an afterthoughtfootnote:[I am not proficient at accessibility, but I've tried my best. Please let me know of any accessibility issues on this site, and I'll make time to fix them!]. Low-power devices need to be supported.
* *Ecological*. Natural resources must not be wasted, and energy use must be low.

=== Functional Requirements

The site needs to have these features:

* Three sections: about, work and blog.
* Easy for me to write new posts.
* Possible to send a preview link of unfinished posts to friends.
* Supports (nearly) all web browsers and https://gemini.circumlunar.space/[Gemini] clients.
* Has an RSS/Atom feed.
* There's a statistics page that shows how many visits have recently been to which paths, and these statistics are backed up.
* Only I can see 404 requests and server errors.
* Eventually I can use this site also for our family's P2P app backups (more on this in future blog posts).

=== Cross Functional Requirements

All of the above features should be:

* Cheap
* Fast
* Secure
* Low maintenance
* Reasonably good availability

=== Resources

Finally, I have these resources at my disposal:

* I have a few weeks of time.
* I can make web sites.
* I have a lot of motivation to learn to program in Rust.
* I own a Raspberry Pi 3Bfootnote:[Thank you to my wonderful collegues at Filosofian Akatemia for this thoughtful gift.], that's been sitting in a bookshelf since 2016.
* Our apartment building has a very good internet connection.
* I have https://posteo.de[a green email provider] that gives me 2GB of storage.

== The Part Where I Explain How It Works

With that out of the way, let's get down to the nitty-gritty. If you're not interested in the technical side of things, you can <<_conclusion,skip to conclusion>>.

=== Hardware

As you should already know by now, I decided to use my Raspberry Pi 3 B for hosting.
Because I'm a full-time activist, every euro I spend shortens the time I can use for activism before I need to find income.
That means that especially recurring charges add up really fast.
Even a modest 5€ per month for a VM is not nothing for me.
Also for environmental reasons, I try my best to avoid being the reason new hardware gets made.

Unfortunately the Pi didn't come with a charger, memory card nor heatsinks, so I did have to buy them new.
Together that cost me 53€.

=== OS

Because I only use the Pi as a server, a headless installation of https://www.raspberrypi.com/software/operating-systems/[Raspberry Pi OS Lite] was the obvious choice.
After that https://github.com/ttiurani/tiuraniemi.github.io/tree/main/deploy#initial-setup[I documented] in Githubfootnote:[I'm in the process of moving to Codeberg, but unfortunately not there yet. The issue is that I rely on Github Actions quite a lot, and haven't had time to investigate how Codeberg's CI can be configured.] the steps needed to set up SSH, forward ports in my home router, and point Cloudflare's DNSfootnote:[I really don't want to use Cloudflare, but decided to compromise for now, because there's already a dynamic IP client for it. Do tell me if there is a more ethical DNS with an API!] to the IP address.

For reasons I'll explain in a future blog post, I also needed a newer libc than was included in Debian stable ("bullseye"), which meant I had to upgrade to testing ("bookworm").
Because I only use the essentials from the OS, everything luckily works just fine.

To make sure I don't miss out on security patches, I run https://github.com/ttiurani/tiuraniemi.github.io/blob/main/.github/workflows/upgrade.yml[a nightly OS upgrade] in a CI using Ansible, which also reboots the server if that's needed.
I'm aware that this can cause the entire site to break horribly, which is why I set up an Uptime Robot monitor pinging the site, so that I know when it broke.
(And yes, I know a monitor can't prevent downtime, keep on reading.)

Finally, I https://github.com/ttiurani/tiuraniemi.github.io/tree/main/deploy#9-lower-energy-consumption[lowered the energy consumption] of the Pi by turning off all unnecessary services.
With everything turned off, the board should use between 1W and 3W, costing me under 2€ per year in electricity.

=== Web Content

I knew I needed to output both https://gemini.circumlunar.space/docs/gemtext.gmi[Gemtext] and HTML from my blog posts.
I thought about Markdown but ended up going with AsciiDoc because I will likely need the built-in bibliography support for some posts.

There was no Gemini converter for AsciiDoctor.Js so https://github.com/ttiurani/asciidoctorjs-gemini-converter[I made my own].
While I was at it, I also made https://github.com/ttiurani/asciidoctorjs-json-converter[a converter to get JSON metadata out of AsciiDocs].

For CSS/JS I opted to go with https://kit.svelte.dev/[SvelteKit] using adapter-static, which has been a delight.
Unfortunately I didn't yet figure out a way to wire up Asciidoctor.js to SvelteKit, so I use a hacky https://github.com/ttiurani/tiuraniemi.github.io/blob/main/scripts/generateBlogSources.cjs[pre-build script] to generate svelte filesfootnote:[This is something I'm planning to try and integrate directly into SvelteKit so that I'd immediately see changes I make to the AsciiDoc sources.], Gemtext files and OpenGraph images.

=== HTTP and Gemini Servers

For HTTP I decided to go with https://github.com/http-rs/tide[tide web framework for Rust].
Now I can almost hear some of you thinking I should have just installed nginx/acme.sh or [insert your favorite web server here] and be done with it, but bear with me, I had my reasons.

First of all, I many other plans for the HTTP server than just serving static files via HTTP.
Second, I wanted an in-memory cache which is smart enough to inline CSS for cold loads, but not internal navigation (this has to do with how SvelteKit works).
Third, I wanted to learn how to write Rust.

For Gemini, I choosed to go with the very nice https://github.com/mbrubeck/agate[Agate server].
It works as advertised, no complaints.

== Conclusion

What do you stand for and how does that show in what you build?
