---
- hosts: tiuraniemi.org
  become: true
  become_user: root
  tasks:
      - name: Install pip3
        apt:
            name: python3-pip
      - name: Install virtualenv
        pip:
            name: virtualenv
      - name: Create HTML directory
        file:
            path: /srv/www/content
            state: directory
      - name: Create HTML logs directory
        file:
            path: /srv/www/logs
            state: directory
      - name: Create HTML metrics directory
        file:
            path: /srv/www/metrics
            state: directory
      - name: Create directory for ACME certificates
        file:
            path: /srv/www/.certificates
            state: directory
      - name: Create Gemini directory
        file:
            path: /srv/gemini/content
            state: directory
      - name: Create peermerge directory
        file:
            path: /srv/peermerge/content
            state: directory
      - name: Create backup directory
        file:
            path: /srv/backup
            state: directory
