---
- hosts: tiuraniemi.org
  become: true
  become_user: root
  tasks:
      - name: Synchronize HTML files
        ansible.posix.synchronize:
            src: ../dist/html/
            dest: /srv/www/content/
            delete: yes
            rsync_opts:
                - '--chown=root:root'
      - name: Synchronize Gemini files
        ansible.posix.synchronize:
            src: ../dist/gemini/
            dest: /srv/gemini/content/
            delete: yes
            rsync_opts:
                - '--chown=root:root'
      - name: Bust extendedmind server cache
        ansible.builtin.command: /opt/extendedmind_server-{{ extendedmind_server_version }} --admin-socket-file /var/run/extendedmind_server.sock bust-cache
      - name: Copy cache warm script
        ansible.builtin.copy:
            src: ../dist/scripts/warm-cache.sh
            dest: '/opt/warm-cache.sh'
            owner: root
            group: root
            mode: '0744'
      - name: Warm cache
        ansible.builtin.command: /opt/warm-cache.sh
