---
- hosts: tiuraniemi.org
  become: true
  become_user: root
  tasks:
      - name: Synchronize HTML files
        ansible.posix.synchronize:
            src: ../dist/html/
            dest: /var/opt/extendedmind/www/
            delete: yes
            rsync_opts:
                - '--chown=extendedmind:extendedmind'
                - '--chmod=D700,F600'
      - name: Synchronize Gemini files
        ansible.posix.synchronize:
            src: ../dist/gemini/
            dest: /var/opt/agate/content/
            delete: yes
            rsync_opts:
                - '--chown=agate:agate'
                - '--chmod=D700,F600'
      - name: Bust extendedmind server cache
        ansible.builtin.command: /opt/extendedmind/{{ extendedmind_server_version }}/extendedmind_server --admin-socket-file /var/opt/extendedmind/extendedmind_server.sock bust-cache
      - name: Copy cache warm script
        ansible.builtin.copy:
            src: ../dist/scripts/warm-cache.sh
            dest: '/opt/warm-cache.sh'
            owner: root
            group: root
            mode: '0744'
      - name: Warm cache
        ansible.builtin.command: /opt/warm-cache.sh
